# Generated by Django 5.1 on 2024-10-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('politics', 'Politics'), ('health', 'Health'), ('education', 'Education'), ('science', 'Science'), ('business', 'Business'), ('travel', 'Travel'), ('fashion', 'Fashion')], max_length=50),
        ),
    ]
